### ISSUE TITLE
MacOS打开AndroidUISpy探测不到已本地连接的设备

### ISSUE THREAD

**Issue by jef-chen** [qtacore/AndroidUISpy#3]
`adb devices`是可以探测到连接设备的
<img width="240" alt="2019-02-20 10 57 30" src="https://user-images.githubusercontent.com/41981207/53063258-758ca580-34fe-11e9-9171-ff9c5f2726e9.png">

**Comment by drunkdream** [comment]
一般这种情况是因为拷贝测试桩失败导致，可以先在`adb shell`里执行`rm -r /data/local/tmp/qt4a`，删除测试桩目录来解决

**Comment by jef-chen** [comment]
删除也没有效果，UISpy仍然探测不到任何设备
<img width="1021" alt="2019-02-22 11 07 19" src="https://user-images.githubusercontent.com/41981207/53217200-1eb7d500-3692-11e9-98ed-2483cf757e2e.png">

**Comment by drunkdream** [comment]
可以尝试手动拷贝测试桩来解决：
```
$ qt4a-manage install-driver -f
```
再重启UISpy

**Comment by jef-chen** [comment]
<img width="599" alt="2019-02-22 11 13 14" src="https://user-images.githubusercontent.com/41981207/53217431-dfd64f00-3692-11e9-9c01-a2b71e0a8c98.png">

重启UISpy仍然没有

<img width="1040" alt="2019-02-22 11 14 30" src="https://user-images.githubusercontent.com/41981207/53217464-0b593980-3693-11e9-9156-d4d50707f4eb.png">

**Comment by drunkdream** [comment]
建议拔掉其余两台设备，只留一台设备，怀疑是某台有问题导致卡住了

**Comment by jef-chen** [comment]
ok,确实是多设备的问题，谢谢解答！
