### ISSUE TITLE
查找控件失败

### ISSUE THREAD

**Issue by qige96** [qtacore/AndroidUISpy#5]
![image](https://user-images.githubusercontent.com/22453752/54901350-24af0900-4f11-11e9-80ae-85e5ad67e8ee.png)
如图所示，使用v2.5.1.4的release，win10系统，连接小米手机的时候哟这个报错，大佬们知道怎么回事吗？

**Comment by drunkdream** [comment]
非root手机只能探测debug应用，如果没有debug应用，可以选择使用QT4A对应用进行重打包，可以参考[文档](https://qt4a.readthedocs.io/zh_CN/latest/testcase.html#id6)
