### ISSUE TITLE
换域名才能打开调试页面，Androiduispy上没有选中态

### ISSUE THREAD

**Issue by 812865052** [qtacore/AndroidUISpy#8]
主要有两个问题：
1、把appspot.ocm换为netlify.com才能打开调试页面
2、打开调试页面后，点击网页上的节点，Androiduispy上没有选中态，但是真机是有选中态

**Comment by drunkdream** [comment]
有截图吗

**Comment by 812865052** [comment]
![image](https://user-images.githubusercontent.com/12646048/57822032-4a47e880-77c5-11e9-8beb-f5a893978a7d.png)
![image](https://user-images.githubusercontent.com/12646048/57822046-559b1400-77c5-11e9-8cc0-0738172df5f4.png)

**Comment by drunkdream** [comment]
第一个问题我本地用mac测试是ok的，打开的已经是`.netlify.com`域名了
第二个问题是因为这个是WebView控件，只有在使用Chrome远程调试的时候，控件才会有阴影
